// Code generated by protoc-gen-go. DO NOT EDIT.
// source: user.proto

package user

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CreateUserRequest struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{0}
}

func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (m *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(m, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type CreateUserResponse struct {
	Uid                  string   `protobuf:"bytes,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Email                string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserResponse) Reset()         { *m = CreateUserResponse{} }
func (m *CreateUserResponse) String() string { return proto.CompactTextString(m) }
func (*CreateUserResponse) ProtoMessage()    {}
func (*CreateUserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_116e343673f7ffaf, []int{1}
}

func (m *CreateUserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserResponse.Unmarshal(m, b)
}
func (m *CreateUserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserResponse.Marshal(b, m, deterministic)
}
func (m *CreateUserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserResponse.Merge(m, src)
}
func (m *CreateUserResponse) XXX_Size() int {
	return xxx_messageInfo_CreateUserResponse.Size(m)
}
func (m *CreateUserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserResponse proto.InternalMessageInfo

func (m *CreateUserResponse) GetUid() string {
	if m != nil {
		return m.Uid
	}
	return ""
}

func (m *CreateUserResponse) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "CreateUserRequest")
	proto.RegisterType((*CreateUserResponse)(nil), "CreateUserResponse")
}

func init() { proto.RegisterFile("user.proto", fileDescriptor_116e343673f7ffaf) }

var fileDescriptor_116e343673f7ffaf = []byte{
	// 201 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x8f, 0x31, 0x4b, 0xc6, 0x30,
	0x10, 0x86, 0xf9, 0xaa, 0x16, 0xbd, 0x49, 0xa3, 0x43, 0xe9, 0x24, 0x9d, 0x5c, 0x4c, 0x50, 0x11,
	0x11, 0x9c, 0x14, 0xff, 0x40, 0xc1, 0xc5, 0x2d, 0x69, 0x8f, 0x1a, 0x30, 0xbd, 0x7a, 0x97, 0x54,
	0xfc, 0xf7, 0xd2, 0x56, 0xfc, 0x0a, 0xdd, 0xde, 0x97, 0xe3, 0x9e, 0xbb, 0x07, 0x20, 0x09, 0xb2,
	0x1e, 0x98, 0x22, 0x55, 0xaf, 0x70, 0xf6, 0xc2, 0x68, 0x23, 0xbe, 0x09, 0x72, 0x8d, 0x5f, 0x09,
	0x25, 0xaa, 0x0b, 0x38, 0xc2, 0x60, 0xfd, 0x67, 0xb1, 0xbb, 0xdc, 0x5d, 0x9d, 0xd4, 0x4b, 0x51,
	0x25, 0x1c, 0x0f, 0x56, 0xe4, 0x9b, 0xb8, 0x2d, 0xb2, 0x79, 0xf0, 0xdf, 0xab, 0x27, 0x50, 0x6b,
	0x8c, 0x0c, 0xd4, 0x0b, 0xaa, 0x53, 0x38, 0x48, 0xbe, 0xfd, 0xa3, 0x4c, 0x71, 0x4f, 0xce, 0x56,
	0xe4, 0xdb, 0x47, 0x38, 0x9c, 0xf6, 0xd4, 0x0d, 0xe4, 0x0b, 0x45, 0x29, 0xbd, 0xf9, 0xaa, 0x3c,
	0xd7, 0xdb, 0x13, 0xcf, 0x0f, 0xef, 0xf7, 0x9d, 0x8f, 0x1f, 0xc9, 0xe9, 0x86, 0x82, 0x19, 0x6d,
	0xfb, 0x13, 0x9c, 0x65, 0xeb, 0x6c, 0x4f, 0xa3, 0xe9, 0xe8, 0x3a, 0xf8, 0x86, 0x49, 0x90, 0x47,
	0xdf, 0xa0, 0x98, 0xd9, 0xd9, 0x4c, 0xfa, 0x2e, 0x9f, 0xf3, 0xdd, 0x6f, 0x00, 0x00, 0x00, 0xff,
	0xff, 0x02, 0x8d, 0x5d, 0x4e, 0x0d, 0x01, 0x00, 0x00,
}
